#!/bin/sh

# This script lives in the bare repo on beech, which gets pushes for deployment
# to the live site. This script actually performs the deployment below.

#git --work-tree=/home/mkm/virtuals/mike/httpdocs/photoalbum --git-dir=/home/mkm/virtuals/mike/httpdocs/photoalbum/.git checkout -f

set -x

git --work-tree=/home/mkm/virtuals/mike/httpdocs/photoalbum --git-dir=/home/mkm/virtuals/mike/httpdocs/photoalbum/.git pull

cd /home/mkm/virtuals/mike/httpdocs/photoalbum 
bower install
npm install
grunt dev

# using nodemon don't need a restart
#sudo systemctl restart nodepa

set +x

echo "Hooray, the new version is published! Hopefully"


