#!/bin/sh

# This script lives in the bare repo on beech, which gets pushes for deployment
# to the live site. This script actually performs the deployment below.

#git --work-tree=/home/mkm/virtuals/mike/httpdocs/photoalbum --git-dir=/home/mkm/virtuals/mike/httpdocs/photoalbum/.git checkout -f

# Only execute on beech

uname=$(uname -a | awk '{print $2}')
if [[ "$uname" != "beech" ]] ; then
   echo "not on beech, aborting"
   exit
fi

set -x

git --work-tree=/home/mkm/virtuals/mike/httpdocs/photoalbum --git-dir=/home/mkm/virtuals/mike/httpdocs/photoalbum/.git pull

cd /home/mkm/virtuals/mike/httpdocs/photoalbum 
bower install
npm install
grunt dev

# using nodemon don't need a restart
#sudo systemctl restart nodepa

set +x

echo "Hooray, the new version is published! Hopefully"

# Finally update self!
cp hooks/post-receive /home/mkm/photoalbum.git/hooks 
